from __future__ import annotations

import asyncio
import functools
import hashlib
import inspect
import linecache
import threading
import time
import traceback
from collections import defaultdict
from collections.abc import Awaitable, Callable
from pathlib import Path
from typing import Any

from .model import Event, StackSnapshot
from .session import SessionStore

# Internal asyncio coroutine names generated by the event loop itself.
# Tasks with these names are infrastructure, not user code, so we skip tracing
# them to avoid polluting the session with noise.
_INTERNAL_TASK_NAMES: frozenset[str] = frozenset(
    {
        "instrumented",
        "shutdown_asyncgens",
        "shutdown_default_executor",
    }
)


class AsyncioTracer:
    def __init__(self, store: SessionStore) -> None:
        self.store = store
        self._installed = False
        self._originals: dict[tuple[Any, str], Any] = {}
        self._latest_failure_by_parent: dict[int, dict[str, Any]] = {}
        self._timeout_scopes_by_parent: dict[int, list[dict[str, Any]]] = {}
        self._timeout_cm_scopes_by_task: dict[int, list[dict[str, Any]]] = {}
        self._active_blocks_by_task: dict[int, list[dict[str, Any]]] = {}
        self._resource_owners: dict[str, dict[int, int]] = defaultdict(dict)
        self._shielded_task_ids: set[int] = set()
        self._resource_labels: dict[int, str] = {}
        self._lock = threading.RLock()

    def install(self) -> None:
        with self._lock:
            if self._installed:
                return
            self._patch(asyncio, "run", self._wrap_asyncio_run(asyncio.run))
            self._patch(
                asyncio, "create_task", self._wrap_create_task(asyncio.create_task)
            )
            self._patch(
                asyncio.BaseEventLoop,
                "create_task",
                self._wrap_loop_create_task(asyncio.BaseEventLoop.create_task),
            )
            self._patch(
                asyncio,
                "sleep",
                self._wrap_async_function(
                    asyncio.sleep, "sleep", lambda _args, _kwargs: "sleep"
                ),
            )
            self._patch(
                asyncio,
                "gather",
                self._wrap_async_function(
                    asyncio.gather, "gather", lambda _args, _kwargs: "gather"
                ),
            )
            self._patch(
                asyncio,
                "wait",
                self._wrap_async_function(
                    asyncio.wait, "wait", lambda _args, _kwargs: "wait"
                ),
            )
            self._patch(asyncio, "wait_for", self._wrap_wait_for(asyncio.wait_for))
            self._patch(
                asyncio.Queue,
                "get",
                self._wrap_method(
                    asyncio.Queue.get,
                    "queue_get",
                    lambda args, _kwargs: f"queue:{id(args[0])}",
                ),
            )
            self._patch(
                asyncio.Queue,
                "put",
                self._wrap_method(
                    asyncio.Queue.put,
                    "queue_put",
                    lambda args, _kwargs: f"queue:{id(args[0])}",
                ),
            )
            self._patch(
                asyncio.Lock,
                "acquire",
                self._wrap_method(
                    asyncio.Lock.acquire,
                    "lock_acquire",
                    lambda args, _kwargs: f"lock:{id(args[0])}",
                ),
            )
            self._patch(
                asyncio.Lock,
                "release",
                self._wrap_release_method(
                    asyncio.Lock.release,
                    lambda args, _kwargs: f"lock:{id(args[0])}",
                ),
            )
            self._patch(
                asyncio.Semaphore,
                "acquire",
                self._wrap_method(
                    asyncio.Semaphore.acquire,
                    "semaphore_acquire",
                    lambda args, _kwargs: f"semaphore:{id(args[0])}",
                ),
            )
            self._patch(
                asyncio.Semaphore,
                "release",
                self._wrap_release_method(
                    asyncio.Semaphore.release,
                    lambda args, _kwargs: f"semaphore:{id(args[0])}",
                ),
            )
            self._patch(
                asyncio.Event,
                "wait",
                self._wrap_method(
                    asyncio.Event.wait,
                    "event_wait",
                    lambda args, _kwargs: f"event:{id(args[0])}",
                ),
            )
            self._patch(
                asyncio.Condition,
                "wait",
                self._wrap_method(
                    asyncio.Condition.wait,
                    "condition_wait",
                    lambda args, _kwargs: f"condition:{id(args[0])}",
                ),
            )
            self._patch(asyncio, "shield", self._wrap_shield(asyncio.shield))
            self._patch(
                asyncio.TaskGroup,
                "__aenter__",
                self._wrap_taskgroup_aenter(asyncio.TaskGroup.__aenter__),
            )
            self._patch(
                asyncio.TaskGroup,
                "__aexit__",
                self._wrap_taskgroup_aexit(asyncio.TaskGroup.__aexit__),
            )
            if hasattr(asyncio, "Barrier"):
                self._patch(
                    asyncio.Barrier,
                    "wait",
                    self._wrap_method(
                        asyncio.Barrier.wait,
                        "barrier_wait",
                        lambda args, _kwargs: f"barrier:{id(args[0])}",
                    ),
                )
            if hasattr(asyncio, "Timeout"):
                self._patch(
                    asyncio.Timeout,
                    "__aenter__",
                    self._wrap_timeout_aenter(asyncio.Timeout.__aenter__),
                )
                self._patch(
                    asyncio.Timeout,
                    "__aexit__",
                    self._wrap_timeout_aexit(asyncio.Timeout.__aexit__),
                )
            self._installed = True

    def uninstall(self) -> None:
        with self._lock:
            for (owner, attr), original in reversed(list(self._originals.items())):
                setattr(owner, attr, original)
            self._originals.clear()
            self._installed = False

    def label_resource(self, resource: Any, name: str) -> None:
        """Annotate a runtime resource with a human-readable label."""
        self._resource_labels[id(resource)] = name

    def _wrap_taskgroup_aenter(
        self, original: Callable[..., Any]
    ) -> Callable[..., Any]:
        tracer = self

        @functools.wraps(original)
        async def wrapper(group_obj: Any) -> Any:
            task = asyncio.current_task()
            task_id = id(task) if task is not None else None
            task_name = task.get_name() if task is not None else None
            group_id = id(group_obj)
            tracer._emit_event(
                kind="taskgroup.enter",
                task_id=task_id,
                task_name=task_name,
                state="RUNNING",
                metadata={"group_id": group_id},
            )
            return await original(group_obj)

        return wrapper

    def _wrap_taskgroup_aexit(self, original: Callable[..., Any]) -> Callable[..., Any]:
        tracer = self

        @functools.wraps(original)
        async def wrapper(
            group_obj: Any, exc_type: Any, exc_val: Any, exc_tb: Any
        ) -> Any:
            task = asyncio.current_task()
            task_id = id(task) if task is not None else None
            task_name = task.get_name() if task is not None else None
            group_id = id(group_obj)
            try:
                result = await original(group_obj, exc_type, exc_val, exc_tb)
            except asyncio.CancelledError:
                tracer._emit_event(
                    kind="taskgroup.exit",
                    task_id=task_id,
                    task_name=task_name,
                    state="RUNNING",
                    metadata={"group_id": group_id, "exit_status": "cancelled"},
                )
                raise
            except BaseException:
                tracer._emit_event(
                    kind="taskgroup.exit",
                    task_id=task_id,
                    task_name=task_name,
                    state="RUNNING",
                    metadata={"group_id": group_id, "exit_status": "error"},
                )
                raise
            else:
                if exc_type is not None:
                    exit_status = "error_absorbed"
                else:
                    exit_status = "normal"
                tracer._emit_event(
                    kind="taskgroup.exit",
                    task_id=task_id,
                    task_name=task_name,
                    state="RUNNING",
                    metadata={"group_id": group_id, "exit_status": exit_status},
                )
                return result

        return wrapper

    def _wrap_shield(self, original: Callable[..., Any]) -> Callable[..., Any]:
        tracer = self

        @functools.wraps(original)
        def wrapper(arg: Any) -> Any:
            task = asyncio.current_task()
            outer_task_id = id(task) if task is not None else None
            outer_task_name = task.get_name() if task is not None else None
            inner_task = arg if isinstance(arg, asyncio.Task) else None
            inner_task_id = id(inner_task) if inner_task is not None else None
            inner_task_name = inner_task.get_name() if inner_task is not None else None
            if inner_task_id is not None:
                tracer._shielded_task_ids.add(inner_task_id)
            tracer._emit_event(
                kind="task.shield",
                task_id=outer_task_id,
                task_name=outer_task_name,
                state="RUNNING",
                metadata={
                    "shielded_task_id": inner_task_id,
                    "shielded_task_name": inner_task_name,
                },
            )
            return original(arg)

        return wrapper

    def _wrap_timeout_aenter(self, original: Callable[..., Any]) -> Callable[..., Any]:
        tracer = self

        @functools.wraps(original)
        async def wrapper(timeout_obj: Any) -> Any:
            task = asyncio.current_task()
            task_id = id(task) if task is not None else None
            task_name = task.get_name() if task is not None else None
            when = timeout_obj.when()
            timeout_seconds = (
                round(when - asyncio.get_event_loop().time(), 3)
                if when is not None
                else None
            )
            scope = {"timeout_seconds": timeout_seconds}
            if task_id is not None:
                tracer._timeout_cm_scopes_by_task.setdefault(task_id, []).append(scope)
            tracer._emit_event(
                kind="task.block",
                task_id=task_id,
                task_name=task_name,
                state="BLOCKED",
                reason="timeout_cm",
                resource_id="timeout_cm",
                metadata={"timeout_seconds": timeout_seconds},
            )
            return await original(timeout_obj)

        return wrapper

    def _wrap_timeout_aexit(self, original: Callable[..., Any]) -> Callable[..., Any]:
        tracer = self

        @functools.wraps(original)
        async def wrapper(
            timeout_obj: Any,
            exc_type: Any,
            exc_val: Any,
            exc_tb: Any,
        ) -> Any:
            task = asyncio.current_task()
            task_id = id(task) if task is not None else None
            task_name = task.get_name() if task is not None else None
            if task_id is not None:
                scopes = tracer._timeout_cm_scopes_by_task.get(task_id, [])
                if scopes:
                    scopes.pop()
                if not scopes and task_id in tracer._timeout_cm_scopes_by_task:
                    del tracer._timeout_cm_scopes_by_task[task_id]
            tracer._emit_event(
                kind="task.unblock",
                task_id=task_id,
                task_name=task_name,
                state="RUNNING",
                reason="timeout_cm",
                resource_id="timeout_cm",
            )
            return await original(timeout_obj, exc_type, exc_val, exc_tb)

        return wrapper

    def _patch(self, owner: Any, attr: str, replacement: Any) -> None:
        key = (owner, attr)
        if key not in self._originals:
            self._originals[key] = getattr(owner, attr)
        setattr(owner, attr, replacement)

    def _wrap_asyncio_run(self, original: Callable[..., Any]) -> Callable[..., Any]:
        @functools.wraps(original)
        def wrapper(main: Awaitable[Any], *args: Any, **kwargs: Any) -> Any:
            async def instrumented() -> Any:
                loop = asyncio.get_running_loop()
                current = asyncio.current_task(loop=loop)
                task_id = id(current) if current is not None else None
                task_name = self._task_name(main, None)
                root_metadata = {
                    "loop_id": id(loop),
                    "task_role": "main",
                    "runtime_origin": "asyncio.run",
                }
                self._emit_event(
                    kind="task.create",
                    task_id=task_id,
                    task_name=task_name,
                    parent_task_id=None,
                    state="READY",
                    metadata=root_metadata,
                )
                self._emit_event(
                    kind="task.start",
                    task_id=task_id,
                    task_name=task_name,
                    parent_task_id=None,
                    state="RUNNING",
                    metadata=root_metadata,
                )
                self._emit_event(
                    kind="runtime.loop", state="RUNNING", metadata={"loop_id": id(loop)}
                )
                if current is not None:
                    self._emit_stack(current)
                try:
                    result = await main
                except asyncio.CancelledError:
                    if current is not None:
                        self._emit_stack(current)
                    cancellation_metadata = self._cancellation_metadata(
                        task_id=task_id,
                        parent_task_id=None,
                    )
                    self._emit_event(
                        kind="task.cancel",
                        task_id=task_id,
                        task_name=task_name,
                        parent_task_id=None,
                        cancelled_by_task_id=cancellation_metadata[
                            "cancelled_by_task_id"
                        ],
                        cancellation_origin=cancellation_metadata[
                            "cancellation_origin"
                        ],
                        state="CANCELLED",
                        reason="cancelled",
                        metadata={
                            **root_metadata,
                            **cancellation_metadata["metadata"],
                        },
                    )
                    self._pop_active_block(task_id)
                    raise
                except Exception as exc:
                    self._emit_event(
                        kind="task.error",
                        task_id=task_id,
                        task_name=task_name,
                        parent_task_id=None,
                        state="FAILED",
                        reason=exc.__class__.__name__,
                        stack_id=(
                            self._emit_stack(current) if current is not None else None
                        ),
                        metadata={
                            **root_metadata,
                            "error": repr(exc),
                        },
                    )
                    raise
                else:
                    self._emit_event(
                        kind="task.end",
                        task_id=task_id,
                        task_name=task_name,
                        parent_task_id=None,
                        state="DONE",
                        metadata=root_metadata,
                    )
                    return result

            return original(instrumented(), *args, **kwargs)

        return wrapper

    def _wrap_wait_for(
        self, original: Callable[..., Awaitable[Any]]
    ) -> Callable[..., Awaitable[Any]]:
        @functools.wraps(original)
        async def wrapper(
            fut: Awaitable[Any], timeout: float | None, *args: Any, **kwargs: Any
        ) -> Any:
            loop = asyncio.get_running_loop()
            task = asyncio.current_task()
            parent_task_id = id(task) if task is not None else None
            task_name = task.get_name() if task is not None else None
            timeout_scope = {"timeout_seconds": timeout}
            waited = fut
            if inspect.iscoroutine(fut):
                waited = loop.create_task(fut)
            if parent_task_id is not None:
                self._timeout_scopes_by_parent.setdefault(parent_task_id, []).append(
                    timeout_scope
                )
            block_stack_id = self._emit_stack(task) if task is not None else None
            self._emit_event(
                kind="task.block",
                task_id=parent_task_id,
                task_name=task_name,
                state="BLOCKED",
                reason="wait_for",
                resource_id="wait_for",
                stack_id=block_stack_id,
            )
            try:
                return await original(waited, timeout, *args, **kwargs)
            except asyncio.CancelledError:
                self._emit_event(
                    kind="task.unblock",
                    task_id=parent_task_id,
                    task_name=task_name,
                    state="RUNNING",
                    reason="wait_for",
                    resource_id="wait_for",
                )
                if task is not None:
                    self._emit_stack(task)
                raise
            finally:
                if parent_task_id is not None:
                    scopes = self._timeout_scopes_by_parent.get(parent_task_id, [])
                    if scopes:
                        scopes.pop()
                    if not scopes and parent_task_id in self._timeout_scopes_by_parent:
                        del self._timeout_scopes_by_parent[parent_task_id]

        return wrapper

    def _wrap_create_task(
        self, original: Callable[..., asyncio.Task[Any]]
    ) -> Callable[..., asyncio.Task[Any]]:
        @functools.wraps(original)
        def wrapper(coro: Any, *args: Any, **kwargs: Any) -> asyncio.Task[Any]:
            loop = asyncio.get_running_loop()
            task = loop.create_task(coro, *args, **kwargs)
            return task

        return wrapper

    def _wrap_loop_create_task(
        self,
        original: Callable[..., asyncio.Task[Any]],
    ) -> Callable[..., asyncio.Task[Any]]:
        @functools.wraps(original)
        def wrapper(
            loop: asyncio.AbstractEventLoop,
            coro: Any,
            *args: Any,
            **kwargs: Any,
        ) -> asyncio.Task[Any]:
            parent = asyncio.current_task(loop=loop)
            parent_task_id = id(parent) if parent is not None else None
            task_name = self._task_name(coro, kwargs.get("name"))
            if not self._should_trace_task(task_name):
                return original(loop, coro, *args, **kwargs)

            async def instrumented() -> Any:
                current = asyncio.current_task(loop=loop)
                task_id = id(current) if current is not None else None
                self._emit_event(
                    kind="task.start",
                    task_id=task_id,
                    task_name=task_name,
                    parent_task_id=parent_task_id,
                    state="RUNNING",
                )
                if current is not None:
                    self._emit_stack(current)
                try:
                    result = await coro
                except asyncio.CancelledError:
                    if current is not None:
                        self._emit_stack(current)
                    cancellation_metadata = self._cancellation_metadata(
                        task_id=task_id,
                        parent_task_id=parent_task_id,
                    )
                    self._emit_event(
                        kind="task.cancel",
                        task_id=task_id,
                        task_name=task_name,
                        parent_task_id=parent_task_id,
                        cancelled_by_task_id=cancellation_metadata[
                            "cancelled_by_task_id"
                        ],
                        cancellation_origin=cancellation_metadata[
                            "cancellation_origin"
                        ],
                        state="CANCELLED",
                        reason="cancelled",
                        metadata=cancellation_metadata["metadata"],
                    )
                    self._pop_active_block(task_id)
                    raise
                except Exception as exc:
                    if parent_task_id is not None and task_id is not None:
                        self._latest_failure_by_parent[parent_task_id] = {
                            "failed_task_id": task_id,
                            "reason": exc.__class__.__name__,
                        }
                    self._emit_event(
                        kind="task.error",
                        task_id=task_id,
                        task_name=task_name,
                        parent_task_id=parent_task_id,
                        state="FAILED",
                        reason=exc.__class__.__name__,
                        stack_id=(
                            self._emit_stack(current) if current is not None else None
                        ),
                        metadata={"error": repr(exc)},
                    )
                    raise
                else:
                    self._emit_event(
                        kind="task.end",
                        task_id=task_id,
                        task_name=task_name,
                        parent_task_id=parent_task_id,
                        state="DONE",
                    )
                    return result

            task = original(loop, instrumented(), *args, **kwargs)
            self._emit_event(
                kind="task.create",
                task_id=id(task),
                task_name=task_name,
                parent_task_id=parent_task_id,
                state="READY",
            )
            return task

        return wrapper

    def _wrap_async_function(
        self,
        original: Callable[..., Awaitable[Any]],
        reason: str,
        resource_factory: Callable[[tuple[Any, ...], dict[str, Any]], str | None],
    ) -> Callable[..., Awaitable[Any]]:
        @functools.wraps(original)
        async def wrapper(*args: Any, **kwargs: Any) -> Any:
            task = asyncio.current_task()
            task_id = id(task) if task is not None else None
            task_name = task.get_name() if task is not None else None
            resource_id = resource_factory(args, kwargs)
            metadata = self._resource_metadata(reason, resource_id, args)
            self._push_active_block(
                task_id=task_id,
                reason=reason,
                resource_id=resource_id,
                metadata=metadata,
            )
            block_stack_id = self._emit_stack(task) if task is not None else None
            self._emit_event(
                kind="task.block",
                task_id=task_id,
                task_name=task_name,
                state="BLOCKED",
                reason=reason,
                resource_id=resource_id,
                stack_id=block_stack_id,
                metadata=metadata,
            )
            try:
                result = await original(*args, **kwargs)
            except asyncio.CancelledError:
                self._emit_event(
                    kind="task.unblock",
                    task_id=task_id,
                    task_name=task_name,
                    state="RUNNING",
                    reason=reason,
                    resource_id=resource_id,
                )
                if task is not None:
                    self._emit_stack(task)
                raise
            else:
                self._pop_active_block(task_id)
                self._emit_event(
                    kind="task.unblock",
                    task_id=task_id,
                    task_name=task_name,
                    state="RUNNING",
                    reason=reason,
                    resource_id=resource_id,
                )
                if task is not None:
                    self._emit_stack(task)
                return result

        return wrapper

    def _wrap_method(
        self,
        original: Callable[..., Awaitable[Any]],
        reason: str,
        resource_factory: Callable[[tuple[Any, ...], dict[str, Any]], str | None],
    ) -> Callable[..., Awaitable[Any]]:
        async def wrapper(*args: Any, **kwargs: Any) -> Any:
            task = asyncio.current_task()
            task_id = id(task) if task is not None else None
            task_name = task.get_name() if task is not None else None
            resource_id = resource_factory(args, kwargs)
            metadata = self._resource_metadata(reason, resource_id, args)
            self._push_active_block(
                task_id=task_id,
                reason=reason,
                resource_id=resource_id,
                metadata=metadata,
            )
            block_stack_id = self._emit_stack(task) if task is not None else None
            self._emit_event(
                kind="task.block",
                task_id=task_id,
                task_name=task_name,
                state="BLOCKED",
                reason=reason,
                resource_id=resource_id,
                stack_id=block_stack_id,
                metadata=metadata,
            )
            try:
                result = await original(*args, **kwargs)
            except asyncio.CancelledError:
                self._emit_event(
                    kind="task.unblock",
                    task_id=task_id,
                    task_name=task_name,
                    state="RUNNING",
                    reason=reason,
                    resource_id=resource_id,
                )
                if task is not None:
                    self._emit_stack(task)
                raise
            else:
                self._register_resource_owner(resource_id, task_id)
                self._pop_active_block(task_id)
                self._emit_event(
                    kind="task.unblock",
                    task_id=task_id,
                    task_name=task_name,
                    state="RUNNING",
                    reason=reason,
                    resource_id=resource_id,
                )
                if task is not None:
                    self._emit_stack(task)
                return result

        return functools.wraps(original)(wrapper)

    def _wrap_release_method(
        self,
        original: Callable[..., Any],
        resource_factory: Callable[[tuple[Any, ...], dict[str, Any]], str | None],
    ) -> Callable[..., Any]:
        def wrapper(*args: Any, **kwargs: Any) -> Any:
            task = asyncio.current_task()
            task_id = id(task) if task is not None else None
            task_name = task.get_name() if task is not None else None
            resource_id = resource_factory(args, kwargs)
            result = original(*args, **kwargs)
            self._unregister_resource_owner(resource_id, task_id)
            if task_id is not None:
                self._emit_event(
                    kind="task.resource",
                    task_id=task_id,
                    task_name=task_name,
                    state="RUNNING",
                    resource_id=None,
                )
            return result

        return functools.wraps(original)(wrapper)

    def _emit_event(
        self,
        *,
        kind: str,
        task_id: int | None = None,
        task_name: str | None = None,
        state: str | None = None,
        reason: str | None = None,
        resource_id: str | None = None,
        parent_task_id: int | None = None,
        cancelled_by_task_id: int | None = None,
        cancellation_origin: str | None = None,
        stack_id: str | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> None:
        event = Event(
            session_id=self.store.session_id,
            seq=self.store.next_seq(),
            ts_ns=time.time_ns(),
            kind=kind,
            task_id=task_id,
            task_name=task_name,
            state=state,
            reason=reason,
            resource_id=resource_id,
            parent_task_id=parent_task_id,
            cancelled_by_task_id=cancelled_by_task_id,
            cancellation_origin=cancellation_origin,
            stack_id=stack_id,
            metadata=metadata or {},
        )
        self.store.append_event(event)

    def _cancellation_metadata(
        self, *, task_id: int | None, parent_task_id: int | None
    ) -> dict[str, Any]:
        metadata = self._active_block_metadata(task_id)
        # asyncio.timeout() context manager — cancels the task itself (no parent needed)
        if task_id is not None:
            cm_scopes = self._timeout_cm_scopes_by_task.get(task_id, [])
            if cm_scopes:
                return {
                    "cancelled_by_task_id": task_id,
                    "cancellation_origin": "timeout_cm",
                    "metadata": {**metadata, **dict(cm_scopes[-1])},
                }
        if parent_task_id is not None:
            timeout_scopes = self._timeout_scopes_by_parent.get(parent_task_id, [])
            if timeout_scopes:
                return {
                    "cancelled_by_task_id": parent_task_id,
                    "cancellation_origin": "timeout",
                    "metadata": {**metadata, **dict(timeout_scopes[-1])},
                }
        if parent_task_id is None:
            return {
                "cancelled_by_task_id": None,
                "cancellation_origin": "external",
                "metadata": metadata,
            }
        failure = self._latest_failure_by_parent.get(parent_task_id)
        if failure is not None:
            return {
                "cancelled_by_task_id": failure["failed_task_id"],
                "cancellation_origin": "sibling_failure",
                "metadata": metadata,
            }
        return {
            "cancelled_by_task_id": parent_task_id,
            "cancellation_origin": "parent_task",
            "metadata": metadata,
        }

    def _push_active_block(
        self,
        *,
        task_id: int | None,
        reason: str,
        resource_id: str | None,
        metadata: dict[str, Any] | None = None,
    ) -> None:
        if task_id is None:
            return
        self._active_blocks_by_task.setdefault(task_id, []).append(
            {
                "blocked_reason": reason,
                "blocked_resource_id": resource_id,
                **(metadata or {}),
            }
        )

    def _pop_active_block(self, task_id: int | None) -> None:
        if task_id is None:
            return
        scopes = self._active_blocks_by_task.get(task_id, [])
        if scopes:
            scopes.pop()
        if not scopes and task_id in self._active_blocks_by_task:
            del self._active_blocks_by_task[task_id]

    def _active_block_metadata(self, task_id: int | None) -> dict[str, Any]:
        if task_id is None:
            return {}
        scopes = self._active_blocks_by_task.get(task_id, [])
        if not scopes:
            return {}
        return dict(scopes[-1])

    def _resource_metadata(
        self, reason: str, resource_id: str | None, args: tuple[Any, ...]
    ) -> dict[str, Any]:
        metadata: dict[str, Any] = {}
        if args:
            resource = args[0]
            label = self._resource_labels.get(id(resource))
            if label is not None:
                metadata["resource_label"] = label
            if reason in {"queue_get", "queue_put"} and isinstance(
                resource, asyncio.Queue
            ):
                metadata["queue_size"] = resource.qsize()
                metadata["queue_maxsize"] = resource.maxsize
            if reason == "event_wait" and isinstance(resource, asyncio.Event):
                metadata["event_is_set"] = resource.is_set()
            if (
                reason == "barrier_wait"
                and hasattr(asyncio, "Barrier")
                and isinstance(resource, asyncio.Barrier)
            ):
                metadata["barrier_parties"] = resource.parties
                metadata["barrier_n_waiting"] = resource.n_waiting
        if resource_id is None or reason not in {"lock_acquire", "semaphore_acquire"}:
            return metadata
        owner_task_ids = self._resource_owner_task_ids(resource_id)
        if owner_task_ids:
            metadata["owner_task_ids"] = owner_task_ids
        return metadata

    def _resource_owner_task_ids(self, resource_id: str) -> list[int]:
        owners = self._resource_owners.get(resource_id, {})
        return sorted(task_id for task_id, count in owners.items() if count > 0)

    def _register_resource_owner(
        self, resource_id: str | None, task_id: int | None
    ) -> None:
        if resource_id is None or task_id is None:
            return
        owners = self._resource_owners.setdefault(resource_id, {})
        owners[task_id] = owners.get(task_id, 0) + 1

    def _unregister_resource_owner(
        self, resource_id: str | None, task_id: int | None
    ) -> None:
        if resource_id is None or task_id is None:
            return
        owners = self._resource_owners.get(resource_id)
        if not owners or task_id not in owners:
            return
        owners[task_id] -= 1
        if owners[task_id] <= 0:
            del owners[task_id]
        if not owners:
            del self._resource_owners[resource_id]

    def _emit_stack(self, task: asyncio.Task[Any]) -> str:
        frames = task.get_stack(limit=16)
        if not frames:
            frame_strings = self._format_extracted_stack(
                traceback.extract_stack(limit=12)
            )
        else:
            frame_strings = []
            for frame in frames:
                frame_strings.extend(self._format_frame(frame))
        stack_blob = "".join(frame_strings)
        stack_id = hashlib.sha1(stack_blob.encode("utf-8")).hexdigest()[:12]
        snapshot = StackSnapshot(
            stack_id=stack_id,
            task_id=id(task),
            ts_ns=time.time_ns(),
            frames=[line.rstrip() for line in frame_strings if line.strip()],
        )
        self.store.add_stack(snapshot)
        self._emit_event(
            kind="stack.snapshot",
            task_id=id(task),
            task_name=task.get_name(),
            state="RUNNING",
            stack_id=stack_id,
        )
        return stack_id

    def _format_extracted_stack(
        self, frames: list[traceback.FrameSummary]
    ) -> list[str]:
        formatted: list[str] = []
        for frame in frames:
            formatted.append(
                self._format_location(
                    filename=frame.filename,
                    line_number=frame.lineno or 0,
                    function_name=frame.name,
                )
            )
            if frame.line:
                formatted.append(frame.line.strip())
        return formatted

    def _format_frame(self, frame: Any) -> list[str]:
        formatted = [
            self._format_location(
                filename=frame.f_code.co_filename,
                line_number=frame.f_lineno,
                function_name=frame.f_code.co_name,
            )
        ]
        source = linecache.getline(frame.f_code.co_filename, frame.f_lineno).strip()
        if source:
            formatted.append(source)
        return formatted

    def _format_location(
        self, *, filename: str, line_number: int, function_name: str
    ) -> str:
        path = Path(filename)
        parts = path.parts
        display_path = "/".join(parts[-2:]) if len(parts) >= 2 else path.name
        return f"{display_path}:{line_number} in {function_name}"

    def _task_name(self, coro: Awaitable[Any], explicit_name: str | None) -> str:
        if explicit_name:
            return explicit_name
        if inspect.iscoroutine(coro):
            code = getattr(coro, "cr_code", None)
            if code is not None:
                return code.co_name
        return getattr(coro, "__qualname__", coro.__class__.__name__)

    def _should_trace_task(self, task_name: str) -> bool:
        return task_name not in _INTERNAL_TASK_NAMES
